In [9]:
import numpy as np
height=np.array([1.78,3.45,1.23,1.87])
weight=np.array([50,70,50,50])
BMI=weight/(height ** 2)
print(BMI)

[15.78083575  5.88111741 33.04911098 14.29837856]


In [11]:
print(BMI[0])
print(BMI[1])
print(BMI[2])
print(BMI[3])
BMI > 13

15.780835753061481
5.881117412308337
33.04911097891467
14.298378563870855


array([ True, False,  True,  True])

## 2 Dimensional array:-

In [51]:
two_d_array=np.array([[12,23,45,54],[21,32,44,"32"]])
print(two_d_array)
print(two_d_array.shape)
(two_d_array[0][3],two_d_array[1][3])

[['12' '23' '45' '54']
 ['21' '32' '44' '32']]
(2, 4)


('54', '32')

In [35]:
print(two_d_array[0:3,:3])

[['12' '23' '45']
 ['21' '32' '44']]


In [37]:
print(two_d_array[1,:])

['21' '32' '44' '32']


In [43]:
baseball=[[12,23,45],[46,54,40],[4,22,21]]
print(baseball)
print()
np_array=np.array(baseball)
print(np_array)

[[12, 23, 45], [46, 54, 40], [4, 22, 21]]

[[12 23 45]
 [46 54 40]
 [ 4 22 21]]


In [60]:
np_array[1:2,0]

array([46])